\c discord;

CREATE USER Admin WITH PASSWORD 'admin123';
CREATE USER Guild_Owner WITH PASSWORD 'owner123';
CREATE USER Discord_User WITH PASSWORD 'user123';

GRANT ALL PRIVILEGES ON GUILD, CHANNEL, D_USER, AUDIT_LOG TO ADMIN;
GRANT SELECT, UPDATE, DELETE, INSERT ON GUILD, CHANNEL, MESSAGE, THREAD, ROLES TO Guild_Owner;
GRANT SELECT ON CHANNEL TO Discord_User;
GRANT INSERT, DELETE, UPDATE ON MESSAGE, THREAD TO Discord_User;

